### ISSUE TITLE
Update Apollo-specific interface

### ISSUE THREAD

**Issue by yuit** [convoyinc/apollo-cache-hermes#171] opened 2017-10-13 21:56 UTC
- [ ]  Rename apollo/Transaction -> `DataProxy` for consistency

- [ ] Update method of `ApolloTrasaction`  class to have similar API as `DataProxy`

**Comment by nevir** [comment] 2017-10-25 14:56
dupe of #179

**Closed by nevir** 2017-10-25 14:56 UTC
